---
- hosts: server
  tasks:
    - name: Setting up the Security Group for new ALB
      ec2_group:
          name: ALB_Security_Group_AWS
          description: Allowing Traffic on port 80 and 443
          region: eu-west-2
          rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0

           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0

           - proto: icmp
             from_port: -1
             to_port: -1
             cidr_ip: 0.0.0.0/0
          rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0
          vpc_id: vpc-0fe6b4ef5ccaa93d1

    - name: setup a simple load balancer
      ec2_elb_lb:
        name: aws-elb-demo
        state: present
        region: eu-west-2
        zones:
          - eu-west-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80

